user 생성과 인증/인가 완성본
promotion-builder/promotion-builder pull request #1
Opened 2024-01-28 02:08 UTC by worldeddt

테스트가 필요한데 피드백 있으면 전달 오네가이

2024-02-04 01:45 UTC, njw1204 requested changes

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/common/security/JwtAuthenticationProvider.java
> +    public String getRefreshToken(String username, List<Role> roles) {
`createRefreshToken` 으로 명명해주세요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/user/controller/UserWebController.java
> +@RequestMapping("/v1/user")
URL에서 `v1`은 모두 빼주세요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/user/controller/dto/CreateUserResponse.java
> +@Getter
DTO 별로 붙는 lombok 어노테이션이 너무 제각각인 것 같은데
최대한 DTO에 붙는 lombok 어노테이션은 `@Data` 하나로 통일하는게 좋을 것 같아요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/user/controller/dto/UserDto.java
> +@Data
DTO 별로 붙는 lombok 어노테이션이 너무 제각각인 것 같은데
최대한 DTO에 붙는 lombok 어노테이션은 `@Data` 하나로 통일하는게 좋을 것 같아요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationService.java
서비스 디렉토리명 services -> application 으로 변경해주세요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/user/repository/UserRepository.java
> +    Optional<User> findUserByUsername(String username);
`findUserByUsernameAndDeletedAtNull` 로 명명해야 의도대로 동작할 것 같아요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/user/repository/UserRepository.java
> +    Optional<User> findUserByRefreshToken(String refreshToken);
`findUserByRefreshTokenAndDeletedAtNull` 로 명명해야 의도대로 동작할 것 같아요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/user/controller/dto/UserSignUpRequest.java
> +    @Schema(description = "유저 역할", example = "USER")
이거는 API request로 입력받을게 아니고 USER 로 고정 부탁드려요

ADMIN 은 운영자 계정인데 아무나 가입시킬 수 없으니 별도로 가입 API 설계하던가 해야될 것 같고요
GUEST 는 비회원 토큰을 의미해서 가입 필요 없고요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/user/controller/dto/UserSignUpRequest.java
> +@Builder
`@Builder` 제거해주세요
DTO는 최대한 `@Data` 하나로 통일

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/authentication/controller/dto/TokenDtoResponse.java
> +    private String grantType;
grantType 필요 없을것 같아요
애플리케이션 계층에서 관리할만한 정보가 아닌듯

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/user/domain/entity/User.java
> +    private UserStatus status;
status는 `'ACTIVE', 'DEACTIVATE'` 로만 구분해주시고 삭제여부는 `deletedAt` 필드로 관리해주세요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +        if (user.getStatus().equals(User.UserStatus.DELETED) ||
삭제 여부는 `deletedAt` 필드로 판단해주세요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +                        .orElseThrow(() -> new BaseException(BaseResponseStatus.RENEW_TOKEN_ERROR_BAD_REFRESH_TOKEN));
리프레시 토큰하고는 별 상관 없는 오류 같은데 올바른 `BaseResponseStatus` 사용 부탁드려요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +        } else if (needNewLogin(accessToken, refreshToken)
짜신 코드만 보면 else if 절에 `needNewLogin` 조건 체크할 필요 없어보입니다

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +
위에 if ~ else if 문에서 무조건 걸려서 이 라인 이후로는 실행될 일이 절대 없는데요? 로직 올바르게 구현하셨는지 체크 부탁드립니다

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +    private boolean reIssueAccessToken(String accessToken) {
메소드명이 의미하는 바를 알기 어려워요 좋은 이름으로 개선하면 좋을 것 같습니다

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +        if (!jwtAuthenticationProvider.validateToken(refreshToken)) {
토큰이 만료됐을때도 재발급하는 로직으로 짜셨는데, 이러면 refreshToken에 유효기간을 설정하는 의미가 없고 그냥 무제한 기간 토큰이랑 똑같아 지는건데 의도하신건지 설계 검토 부탁드려요

2024-02-04 01:45 UTC, njw1204 commented on app/src/main/java/kr/njw/promotionbuilder/user/services/UserServiceImpl.java
> +                .password(bCryptPasswordEncoder.encode(userSignUpRequest.getPassword()))
`BCryptPasswordEncoder`를 여기저기 사용해서 유지보수가 힘들 것 같은데
패스워드 인코딩은 `User` 클래스에 static 메소드 하나 만들어서 진행합시다
메소드명 예시 : `encodePassword`

`BCryptPasswordEncoder`는 `User` 클래스 안에서만 참조합시다

2024-02-07 01:16 UTC, worldeddt commented on app/src/main/resources/application-local.yml
> +      ddl-auto: update
궁금한게 추천하는 이유는 무엇이며 orm을 사용하지 않는 이유능?

2024-02-07 01:17 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +    private boolean reIssueAccessToken(String accessToken) {
access token 재발급을 의도한건데 추천졈..

2024-02-07 01:19 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +        if (!jwtAuthenticationProvider.validateToken(refreshToken)) {
refresh token 만료되면 재로그인이 맞겠쬬?

2024-02-07 01:19 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/user/services/UserServiceImpl.java
> +                .password(bCryptPasswordEncoder.encode(userSignUpRequest.getPassword()))
그럽시다

2024-02-07 01:20 UTC, worldeddt commented
근데 이거 태스크 등록 못하낭

2024-02-10 04:25 UTC, worldeddt commented on .idea/.gitignore
- [ ] idea

2024-02-10 04:50 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/authentication/config/TokenConfig.java
- [] 제거

2024-02-10 04:51 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/authentication/controller/AdministratorApiController.java
> +@RequestMapping("/v1/token")
- [ ] api 수정

2024-02-10 04:53 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/authentication/controller/AdministratorApiController.java
> +    @PostMapping("/reIssue")
- [ ] 재작명

2024-02-10 06:54 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +
- [ ] 로직 점검 후 수정

2024-02-10 06:55 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +        } else if (needNewLogin(accessToken, refreshToken)
- [ ] 로직 점검 후 수정 2

2024-02-10 06:55 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +    private boolean reIssueAccessToken(String accessToken) {
- [ ] 메소드명 수정

2024-02-10 07:12 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/authentication/services/AuthenticationServiceImpl.java
> +        if (!jwtAuthenticationProvider.validateToken(refreshToken)) {
- [ ] refresh token 정책 재수립

2024-02-10 07:31 UTC, worldeddt commented on app/src/main/java/kr/njw/promotionbuilder/user/services/UserServiceImpl.java
> +                .password(bCryptPasswordEncoder.encode(userSignUpRequest.getPassword()))
- [ ] encrypt 메소드 창시

2024-02-10 08:01 UTC, njw1204 commented
- 회원가입시:
  - 업체명 저장 필요
  - API 연동 비밀키 발급 필요 (32글자 랜덤 hex string)
- 본인 회원정보 조회/수정 API 필요: (회원가입시 입력한 정보 조회/수정)
- 비밀키 갱신 API 필요 (32글자 랜덤 hex string)

2024-02-10 08:07 UTC, njw1204 commented
토큰 재발급시: 리프레시 토큰 유효하면, 엑세스 토큰과 리프레시 토큰 둘다 갱신. 리프레시 토큰 무효하면, 둘다 갱신하지 않고 오류 처리

2024-02-25 09:57 UTC, merged